version: '3.2'
services:
  sublet_bot:
    build:
      context: .
    container_name: sublet_bot
    stop_signal: SIGKILL
    ports:
      - 5004:5004
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - ./media:/telegram_bot/media
    environment:
      - LOCAL_ENV=local

    develop:
      watch:
        - action: sync
          path: .
          target: /telegram_bot
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt

  postgres:
    image: postgres
    container_name: sublet_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
